using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UNLowCoder.Core.Data;

namespace UNLowCoder.SourceGen
{
    internal class UnLocodeCodeGeneratorCore
    {
        public UnLocodeCodeGeneratorCore() { }

        public SourceText CreateMainClass(GeneratorDataContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Hauptdatei");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UNLowCoder.Core.Data;");
            if (!string.IsNullOrEmpty(context.Namespace))
                sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine($"public partial class {context.GeneratedClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Countries {}");
            sb.AppendLine("    public static partial class Subdivisions {}");
            sb.AppendLine("    public static partial class Locations {}");
            sb.AppendLine("}");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        public SourceText CreateCountriesClass(GeneratorDataContext context)
        {
            var countries = context.Countries;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Countries Daten");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UNLowCoder.Core.Data;");
            if (!string.IsNullOrEmpty(context.Namespace))
                sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine($"public partial class {context.GeneratedClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Countries");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            var finalCountryNames = new List<string>();

            foreach (var country in countries)
            {
                var cn = GetUniqueName(SafeIdentifier(country.CountryCode), usedNames);
                finalCountryNames.Add(cn);

                var subdivisionsArray = CreateSubdivisionsArray(country.Subdivisions);
                var locationsArray = CreateLocationsArray(country.Locations);

                sb.AppendLine($"        public static UnLocodeCountry {cn} => new UnLocodeCountry(");
                sb.AppendLine($"            \"{Escape(country.CountryCode)}\",");
                sb.AppendLine($"            {EscapeString(country.CountryName)},");
                sb.AppendLine($"            {subdivisionsArray},");
                sb.AppendLine($"            {locationsArray}");
                sb.AppendLine("        );");
            }

            var allName = GetUniqueName("All", usedNames);
            sb.AppendLine($"        public static System.Collections.Generic.IReadOnlyList<UnLocodeCountry> {allName} => new UnLocodeCountry[] {{ {string.Join(", ", finalCountryNames)} }};");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        public SourceText CreateSubdivisionsClass(GeneratorDataContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Subdivisions Daten");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UNLowCoder.Core.Data;");
            if (!string.IsNullOrEmpty(context.Namespace))
                sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine($"public partial class {context.GeneratedClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Subdivisions");
            sb.AppendLine("    {");

            var allSubs = new List<string>();
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var country in context.Countries)
            {
                foreach (var sub in country.Subdivisions)
                {
                    string baseName = SafeIdentifier(sub.CountryCode + "_" + sub.SubdivisionCode);
                    string id = GetUniqueName(baseName, usedNames);

                    sb.AppendLine($"        public static UnLocodeSubdivision {id} => new UnLocodeSubdivision(" +
                                  $"\"{Escape(sub.CountryCode)}\", \"{Escape(sub.SubdivisionCode)}\", {EscapeString(sub.Name)}, {EscapeString(sub.Type)});");
                    allSubs.Add(id);
                }
            }

            var allName = GetUniqueName("All", usedNames);
            sb.AppendLine($"        public static System.Collections.Generic.IReadOnlyList<UnLocodeSubdivision> {allName} => new UnLocodeSubdivision[] {{ {string.Join(", ", allSubs)} }};");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        public SourceText CreateLocationsClass(GeneratorDataContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Locations Daten");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UNLowCoder.Core.Data;");
            if (!string.IsNullOrEmpty(context.Namespace))
                sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine($"public partial class {context.GeneratedClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Locations");
            sb.AppendLine("    {");

            var allLocs = new List<string>();
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var country in context.Countries)
            {
                foreach (var loc in country.Locations)
                {
                    string baseName = SafeIdentifier(loc.CountryCode + loc.LocationCode);
                    string id = GetUniqueName(baseName, usedNames);

                    sb.AppendLine($"        public static UnLocodeLocation {id} => new UnLocodeLocation(" +
                                  $"\"{Escape(loc.CountryCode)}\", " +
                                  $"\"{Escape(loc.LocationCode)}\", " +
                                  $"{EscapeString(loc.Name)}, " +
                                  $"{EscapeString(loc.NameWoDiacritics)}, " +
                                  $"{(loc.SubdivisionCode != null ? EscapeString(loc.SubdivisionCode) : "null")}, " +
                                  $"LocationStatus.{loc.Status}, " +
                                  $"LocationFunction.{loc.Function}, " +
                                  $"{FormatDate(loc.LastUpdateDate)}, " +
                                  $"{EscapeString(loc.IATA)}, " +
                                  $"{FormatCoordinates(loc.Coordinates)}, " +
                                  $"{EscapeString(loc.Remarks)}, " +
                                  $"ChangeIndicator.{loc.Change}" +
                                  $");");
                    allLocs.Add(id);
                }
            }

            var allName = GetUniqueName("All", usedNames);
            sb.AppendLine($"        public static System.Collections.Generic.IReadOnlyList<UnLocodeLocation> {allName} => new UnLocodeLocation[] {{ {string.Join(", ", allLocs)} }};");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        private static string GetUniqueName(string baseName, HashSet<string> usedNames, bool checkOnly = false)
        {
            if (string.Equals(baseName, "region", StringComparison.OrdinalIgnoreCase))
                baseName = "regionX";
            if (string.Equals(baseName, "arctic", StringComparison.OrdinalIgnoreCase))
                baseName = "arcticX";

            string name = baseName;
            int counter = 2;
            while (usedNames.Contains(name))
            {
                name = baseName + "_" + counter;
                counter++;
            }

            if (!checkOnly)
                usedNames.Add(name);

            return name;
        }

        private static string CreateSubdivisionsArray(IReadOnlyList<UnLocodeSubdivision> subs)
        {
            if (subs.Count == 0) return "System.Array.Empty<UnLocodeSubdivision>()";
            var init = string.Join(",\r\n", subs.Select(s =>
                $"new UnLocodeSubdivision(\"{Escape(s.CountryCode)}\", \"{Escape(s.SubdivisionCode)}\", {EscapeString(s.Name)}, {EscapeString(s.Type)})"));
            return $"new UnLocodeSubdivision[] {{ {init} }}";
        }

        private static string CreateLocationsArray(IReadOnlyList<UnLocodeLocation> locs)
        {
            if (locs.Count == 0) return "System.Array.Empty<UnLocodeLocation>()";
            var init = string.Join(",\r\n", locs.Select(l =>
                $"new UnLocodeLocation(" +
                $"\"{Escape(l.CountryCode)}\", " +
                $"\"{Escape(l.LocationCode)}\", " +
                $"{EscapeString(l.Name)}, " +
                $"{EscapeString(l.NameWoDiacritics)}, " +
                $"{(l.SubdivisionCode != null ? EscapeString(l.SubdivisionCode) : "null")}, " +
                $"LocationStatus.{l.Status}, " +
                $"LocationFunction.{l.Function}, " +
                $"{FormatDate(l.LastUpdateDate)}, " +
                $"{EscapeString(l.IATA)}, " +
                $"{FormatCoordinates(l.Coordinates)}, " +
                $"{EscapeString(l.Remarks)}, " +
                $"ChangeIndicator.{l.Change}" +
                $")"
            ));
            return $"new UnLocodeLocation[] {{ {init} }}";
        }

        private static string Escape(string s)
        {
            // Trim und entferne Zeilenumbrüche
            s = s?.Trim();
            s = s.Replace("\r", "").Replace("\n", "");
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeString(string s)
        {
            if (s == null)
                return "null";
            s = s.Trim();
            s = s.Replace("\r", "").Replace("\n", "");
            return $"\"{Escape(s)}\"";
        }

        private static string SafeIdentifier(string s)
        {
            if (string.IsNullOrEmpty(s)) return "_EMPTY";
            s = s.Trim();
            s = s.Replace("\r", "").Replace("\n", "");
            if (!char.IsLetter(s[0])) s = "_" + s;
            var sb = new StringBuilder();
            foreach (var ch in s)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                    sb.Append(ch);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }

        private static string FormatDate(DateTime? dt)
        {
            if (dt == null) return "null";
            var d = dt.Value;
            return $"new System.DateTime({d.Year}, {d.Month}, {d.Day}, 0, 0, 0, System.DateTimeKind.Unspecified)";
        }

        private static string FormatCoordinates(Coordinates? c)
        {
            if (c == null) return "null";
            return $"new Coordinates({c.Latitude.ToString(System.Globalization.CultureInfo.InvariantCulture)}, {c.Longitude.ToString(System.Globalization.CultureInfo.InvariantCulture)})";
        }
    }
}
