// <auto-generated>
// Hauptdatei
// </auto-generated>
using UNLowCoder.Core.Data;
namespace UNLowCoder.Lib;
public partial class UnLocodes
{
    public static partial class Countries {}
    public static partial class Subdivisions {}
    public static partial class Locations {}
}
